9-sort-loops
AleksandrVisik/Home-Work-JS-Basic pull request #6
Opened 2024-03-31 20:07 UTC by AleksandrVisik

2024-04-01 07:43 UTC, GitEsense requested changes
Всё хорошо и работает, но...
У Вас функция модифицирует исходный массив, т.е. если мы вызовем вывод в консоль arr до и после вызова, то arr будет изменён, функция же должна возвращать результирующий массив без модификации.

Так же по поводу сортировки, хорошо бы не "реверсом", передавая необязательный параметр направления сортировки (раз уж Вы решили её реализовать)

2024-04-02 06:43 UTC, AleksandrVisik commented
Подправил

2024-04-02 07:21 UTC, GitEsense requested changes
А функция всё ещё модифицирует исходный массив.
Посмотрите результат, который будет при выполнении
```js
console.log(arr); // исходный массив
console.log(sortArrUp(arr)); // по возрастанию
console.log(sortArrUp(arr, false)); // по убыванию
console.log(arr); // исходный массив

![image](https://github.com/AleksandrVisik/Home-Work-JS-Basic/assets/101252030/8ca9d78f-b2c5-4c01-8411-77eba7a21235)

2024-04-02 07:28 UTC, AleksandrVisik commented
Понял. Буду искать решение.

2024-04-02 07:44 UTC, GitEsense commented
> Понял. Буду искать решение.

Решение довольно простое - посмотрите в сторону деструктур

2024-04-03 07:34 UTC, GitEsense approved these changes
Вот теперь отлично, но к наименованию переменных всё же лучше подходить более "описывающе", ну и придерживаться принципа, что булевы переменные имеют вид что-то вроде
isArray
hasArray
canArray
Из названия переменной мы уже понимаем, что она вернёт булево значение

2024-04-03 07:34 UTC, GitEsense commented on 9-sort-loops/app.js
> +console.log(arr); // исходный массив после вызова функции
Ну итоговый вариант выглядел бы ориентировочно вот так
```js
function orderTemplate(firstNumber, secondNumber, desc) {
    if (!desc) {
        return firstNumber > secondNumber;
    }
    return firstNumber < secondNumber;
}

function sortArrayInAscending(incomingArray, desc = false) {
    const array = [...incomingArray];
    for (let i = 0; i < array.length; i++) {
        for (let j = i; j < array.length; j++) {
            const isExchange = orderTemplate(array[i], array[j], desc);
            if (isExchange) {
                [array[i], array[j]] = [array[j], array[i]];
            }
        }
    }
    return array;
}

console.log(numbers);
console.log('Отсортированный по возрастанию массив:', sortArrayInAscending(numbers));
console.log('Отсортированный по убыванию массив:', sortArrayInAscending(numbers, true));
```

2024-04-03 07:34 UTC, GitEsense commented on 9-sort-loops/app.js
> +    const arrResult = array.slice();
Можно было бы воспользоваться деструктуризацией
```js
const resultArray = [...array];
```
либо через "дефолт" функцию
```js
const resultArray = Array.from(array);
```

2024-04-03 17:12 UTC, AleksandrVisik commented on 9-sort-loops/app.js
> +    const arrResult = array.slice();
Принял к сведению

2024-04-03 17:13 UTC, merged